#!/bin/bash

################################################################
# Hyprland（最小構成）をインストールするためのシェルスクリプト #
################################################################

# 基本パッケージのインストール
sudo pacman -Syu hyprland foot otf-ipafont wofi neovim --needed --noconfirm

# Hyprland の設定ファイルをコピー
mkdir -p $HOME/.config/hypr/
cp /usr/share/hypr/hyprland.conf $HOME/.config/hypr/

# hyprland.conf の編集
# （操作メッセージを無効化）
sed -i "s/autogenerated/#autogenerated/g" $HOME/.config/hypr/hyprland.conf
# （ターミナルを kitty から foot に変更）
sed -i "s/$terminal = kitty/$terminal = foot/g" $HOME/.config/hypr/hyprland.conf
# （CapsLock を Ctrl に変更）
sed -i "s/kb_options =/kb_options = ctrl:nocaps/g" $HOME/.config/hypr/hyprland.conf
# （ターミナルの起動ショートカットを「Super+q」から「Super+Enter」に変更）
sed -i "s/$mainMod, Q, exec, $terminal/$mainMod, RETURN, exec, $terminal/g" $HOME/.config/hypr/hyprland.conf
# （wofi の起動ショートカットを「Super+r」から「Super+Space」に変更）
sed -i "s/$mainMod, R, exec, $menu/$mainMod, SPACE, exec, $menu/g" $HOME/.config/hypr/hyprland.conf

# foot の設定ファイルをコピー
mkdir -p $HOME/.config/foot/
cp /etc/xdg/foot/foot.ini $HOME/.config/foot/

# foot.ini の編集
sed -i "s/# font=monospace:size=8/font=monospace:size=12/g" $HOME/.config/foot/foot.ini
sed -i "s/# pad=0x0/pad=5x5/g" $HOME/.config/foot/foot.ini

# /etc/environment にデフォルトアプリとして Neovim を設定
ETC_ENV="/etc/environment"
sudo sh -c "echo EDITOR=nvim >> $ETC_ENV"

# Hyprland の起動の仕方
# 通常通り、ArchLinux のコンソールでログイン後、
# 「$ Hyprland」と入力すれば、起動する。
